### ISSUE TITLE
Invitation email has no style/help/details

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/aida-ui#183] opened 2018-07-30 17:06 UTC
![screen shot 2018-07-30 at 2 04 47 pm](https://user-images.githubusercontent.com/4836220/43411820-b26461f8-9401-11e8-9c5f-08cad814212f.png)

**Comment by nekron** [comment] 2018-07-30 17:50
Duplicate of instedd/aida#208

**Closed by nekron** 2018-07-30 17:50 UTC
Labels: duplicate
